#!/bin/bash
set -e

ROOT=$(cd "$(dirname "$0")/.."; pwd)

TMP_DIR="/mnt/tmp"
ROOT_IMG="/mnt/root.img"
CACHE_DIR="/mnt/cache/vm"

mkdir -p "$TMP_DIR"

rm -f "$ROOT_IMG"
truncate -s 4G "$ROOT_IMG"
/sbin/mkfs.ext4 -m 0 "$ROOT_IMG"

BUILD_DIR=$(mktemp -d -p "$TMP_DIR")
sudo mount -o loop "$ROOT_IMG" "$BUILD_DIR"
trap 'sudo umount "$BUILD_DIR"; rm -Rf "$BUILD_DIR"' EXIT
set -x

sudo buildctl build \
  --frontend dockerfile.v0 \
  --local context="$ROOT" \
  --local dockerfile="$ROOT/vm/root" \
  --output "type=local,dest=$BUILD_DIR" \
  --import-cache "type=local,src=$CACHE_DIR" \
  --export-cache "type=local,dest=$CACHE_DIR"
