#!/bin/bash
set -e

ROOT=$(cd "$(dirname "$0")/.."; pwd)

ROOT_IMG="$ROOT/tmp/root.img"
BUILD_DIR=$(mktemp -d -p "$ROOT/tmp")
sudo mount -o loop "$ROOT_IMG" "$BUILD_DIR"
trap 'sudo umount "$BUILD_DIR"; rm -Rf "$BUILD_DIR"' EXIT

ls -l $BUILD_DIR/boot/
cp "$BUILD_DIR"/boot/vmlinuz* "$ROOT/tmp/vmlinuz"
