#!/bin/bash
set -e

ROOT=$(cd "$(dirname "$0")/.."; pwd)

BUILD_DIR=$(mktemp -d -p "$ROOT/tmp")
trap 'rm -Rf "$BUILD_DIR"' EXIT
cd "$BUILD_DIR"
git clone https://github.com/thepwagner/archivist.git .

buildctl build \
  --frontend dockerfile.v0 \
  --local context="$BUILD_DIR" \
  --local dockerfile="$BUILD_DIR" \
  --output "type=docker,dest=$BUILD_DIR/image.tar" \
  --progress plain
tar -tvvf "$BUILD_DIR/image.tar"
